apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerservice
  template:
    metadata:
      labels:
        app: customerservice
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: postgresqldb-customer
            - name: POSTGRES_DB
              value: customerservice
            - name: POSTGRES_PASSWORD
              value: "4526357"
            - name: POSTGRES_USER
              value: postgres
          image: mpinchuk/customerservice:latest
          name: customerservice
          ports:
            - containerPort: 8083
              name: rest
            - containerPort: 9090
              name: grpc
