apiVersion: v1
kind: Service
metadata:
  name: customerservice
spec:
  type: LoadBalancer
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
      nodePort: 30164
      protocol: TCP
    - name: grpc
      port: 9090
      targetPort: 9090
      nodePort: 30165
      protocol: TCP
  selector:
    app: customerservice
