apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: customerservice
  name: customerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customerservice
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: customerservice
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: postgresqldb-customer
            - name: POSTGRES_DB
              value: customerservice
            - name: POSTGRES_PASSWORD
              value: "4526357"
            - name: POSTGRES_USER
              value: postgres
          image: mpinchuk/customerservice:latest
          imagePullPolicy: ""
          name: customerservice
          ports:
            - containerPort: 8083
          resources: { }
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgres-data-courier
          persistentVolumeClaim:
            claimName: postgres-data-courier
status: { }
